Install meteor

diff --git a/.openshift/action_hooks/build b/.openshift/action_hooks/build
--- a/.openshift/action_hooks/build
+++ b/.openshift/action_hooks/build
@@ -30,3 +30,24 @@ if [ -f "${OPENSHIFT_REPO_DIR}"/package.json ]; then
    (cd "${OPENSHIFT_REPO_DIR}"; export TMPDIR="/tmp"; npm install -d)
 fi
 
+# Install Meteor.js
+
+source "${OPENSHIFT_REPO_DIR}/.openshift/lib/setup_meteor_env"
+
+if [ -z "${OPENSHIFT_MONGODB_DB_URL}" ]; then
+   echo 1>&2
+   echo "MongoDB not found. Please run:" 1>&2
+   echo "rhc cartridge add -a $OPENSHIFT_APP_NAME -c mongodb-2.2" 1>&2
+   echo "then make a sample commit (add whitespace somewhere) and re-push" 1>&2
+   echo 1>&2
+   exit 5
+fi
+
+if [ ! -d "${METEOR_DIR}" ]; then
+   echo Installing Meteor.js
+   mkdir -p ${METEOR_DIR}/bin
+   curl https://install.meteor.com | PREFIX="${METEOR_DIR}" HOME="${METEOR_DIR}" sh
+   echo "Meteor.js `meteor --version` installed"
+else
+   echo "Meteor.js `meteor --version` already installed"
+fi
